### ISSUE TITLE
install bzip2 fails

### ISSUE THREAD

**Issue by al3x10m** [devkitPro/3ds_portlibs#7]
"make bzip2" works but when running "make install" it also tries to build the binaries for the host and link against an arm library instead of copying the lib to devkit's portlibs directory...

pastebin: http://pastebin.com/T6xXZsD0

**Comment by cadenza-k** [comment]
Seems that you have MinGW + devkitPro,
MinGw use also MSys,

Two identical programs, mean two config for one "named" program, and result in a conflict of placing the content like "c:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible ./libbz2.a when searching for -lbz2" instead of "/c/devkitPro/Portlibs/whatever" (if you set devkitPro at C:\devkitPro)

Hope that helped you.

Eclipse2212

**Comment by WinterMute** [comment]
Fixed with 8b4a20f2fa040097f486a327981560a4e0339c1d @WinterMute WinterMute committed a minute ago
